name: rally_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\image.png
    - assets\app_icon.png

flutter_launcher_icons:
  android: true
  ios: false # Desactiva para iOS si no lo necesitas aún
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # Coincide con tu minSdk en build.gradle.kts
  adaptive_icon_background: "#FFFFFF" # Fondo del ícono adaptativo (opcional, blanco por defecto)
  adaptive_icon_foreground: "assets/app_icon.png" # Imagen para el primer plano (opcional)